languageCode = "en-us"
title = "The Meat Pie Blog"
theme = "hugo-theme-bootstrap4-blog-master"
copyright = "A [Raphael Haddad Project](https://raph.ws) | [Contribute](https://github.com/RaphHaddad/meat-pie-blog)"

[permalinks]
  post = "/:year/:month/:title/"

[params]
  author = "Raphael Haddad"
  sharingicons = false